In [36]:
import os
os.getcwd()

'D:\\darthsai'

In [53]:
import numpy as np
from numpy import genfromtxt
emp=genfromtxt("DS1_C4_S1_Employee_Data_Challenge.csv",delimiter=',',skip_header=1)
emp

array([[ 1., 22.],
       [ 2., 27.],
       [ 3., 31.],
       [ 4., 29.],
       [ 5., 27.],
       [ 6., 26.],
       [ 7., 27.],
       [ 8., 23.],
       [ 9., 27.],
       [10., 32.],
       [11., 28.],
       [12., 27.],
       [13., 22.],
       [14., 27.],
       [15., 35.],
       [16., 33.],
       [17., 28.],
       [18., 22.],
       [19., 25.],
       [20., 27.],
       [21., 37.],
       [22., 27.],
       [23., 24.],
       [24., 27.],
       [25., 28.],
       [26., 26.],
       [27., 27.],
       [28., 27.],
       [29., 29.],
       [30., 49.],
       [31., 26.],
       [32., 32.],
       [33., 26.],
       [34., 24.],
       [35., 24.],
       [36., 23.],
       [37., 28.],
       [38., 28.],
       [39., 22.],
       [40., 26.],
       [41., 32.],
       [42., 35.],
       [43., 33.],
       [44., 31.],
       [45., 30.],
       [46., 36.],
       [47., 22.],
       [48., 23.],
       [49., 32.],
       [50., 34.]])

In [56]:
#task 1
averageage=np.mean(emp[:,1])
print(averageage)

28.26


In [92]:
#task 2
agemorethan25=np.where(emp[:,1]>25)
print(emp[agemorethan25][:,0])
len(emp[agemorethan25])

[ 2.  3.  4.  5.  6.  7.  9. 10. 11. 12. 14. 15. 16. 17. 20. 21. 22. 24.
 25. 26. 27. 28. 29. 30. 31. 32. 33. 37. 38. 40. 41. 42. 43. 44. 45. 46.
 49. 50.]


38

In [89]:
#task 3
agebetween30and35=np.where((emp[:,1]>=30) & (emp[:,1]<=35))
print(emp[agebetween30and35][:,0])

[ 3. 10. 15. 16. 32. 41. 42. 43. 44. 45. 49. 50.]


In [63]:
shop=genfromtxt("DS1_C4_S1_Shopping_Data_Challenge.csv",delimiter=',',skip_header=1)

array([[  1.,  19.,  15.,  39.],
       [  2.,  21.,  15.,  81.],
       [  3.,  20.,  16.,   6.],
       [  4.,  23.,  16.,  77.],
       [  5.,  31.,  17.,  40.],
       [  6.,  22.,  17.,  76.],
       [  7.,  35.,  18.,   6.],
       [  8.,  23.,  18.,  94.],
       [  9.,  64.,  19.,   3.],
       [ 10.,  30.,  19.,  72.],
       [ 11.,  67.,  19.,  14.],
       [ 12.,  35.,  19.,  99.],
       [ 13.,  58.,  20.,  15.],
       [ 14.,  24.,  20.,  77.],
       [ 15.,  37.,  20.,  13.],
       [ 16.,  22.,  20.,  79.],
       [ 17.,  35.,  21.,  35.],
       [ 18.,  20.,  21.,  66.],
       [ 19.,  52.,  23.,  29.],
       [ 20.,  35.,  23.,  98.],
       [ 21.,  35.,  24.,  35.],
       [ 22.,  25.,  24.,  73.],
       [ 23.,  46.,  25.,   5.],
       [ 24.,  31.,  25.,  73.],
       [ 25.,  54.,  28.,  14.],
       [ 26.,  29.,  28.,  82.],
       [ 27.,  45.,  28.,  32.],
       [ 28.,  35.,  28.,  61.],
       [ 29.,  40.,  29.,  31.],
       [ 30.,  23.,  29.,  87.],
       [ 3

In [65]:
#task 1
ssmorethan80=np.where(shop[:,3]>80)
print(shop[ssmorethan80])

[[  2.  21.  15.  81.]
 [  8.  23.  18.  94.]
 [ 12.  35.  19.  99.]
 [ 20.  35.  23.  98.]
 [ 26.  29.  28.  82.]
 [ 30.  23.  29.  87.]
 [ 34.  18.  33.  92.]
 [ 36.  21.  33.  81.]
 [ 42.  24.  38.  92.]
 [124.  39.  69.  91.]
 [128.  40.  71.  95.]
 [136.  29.  73.  88.]
 [142.  32.  75.  93.]
 [144.  32.  76.  87.]
 [146.  28.  77.  97.]
 [150.  34.  78.  90.]
 [152.  39.  78.  88.]
 [156.  27.  78.  89.]
 [162.  29.  79.  83.]
 [164.  31.  81.  93.]
 [168.  33.  86.  95.]
 [174.  36.  87.  92.]
 [176.  30.  88.  86.]
 [180.  35.  93.  90.]
 [182.  32.  97.  86.]
 [184.  29.  98.  88.]
 [186.  30.  99.  97.]
 [190.  36. 103.  85.]
 [194.  38. 113.  91.]
 [200.  30. 137.  83.]]


In [90]:
#task 2
agebetween20and24=np.where((shop[:,1]>=20)&(shop[:,1]<=24))
print(shop[agebetween20and24])


[[  2.  21.  15.  81.  20.]
 [  3.  20.  16.   6.  43.]
 [  4.  23.  16.  77.  44.]
 [  6.  22.  17.  76.  22.]
 [  8.  23.  18.  94.  39.]
 [ 14.  24.  20.  77.  35.]
 [ 16.  22.  20.  79.  15.]
 [ 18.  20.  21.  66.  38.]
 [ 30.  23.  29.  87.  12.]
 [ 32.  21.  30.  73.  40.]
 [ 36.  21.  33.  81.  18.]
 [ 40.  20.  37.  75.  37.]
 [ 42.  24.  38.  92.  22.]
 [ 46.  24.  39.  65.  29.]
 [ 79.  23.  54.  52.  30.]
 [ 85.  21.  54.  57.  38.]
 [ 88.  22.  57.  55.  34.]
 [ 96.  24.  60.  52.  14.]
 [100.  20.  61.  49.  39.]
 [101.  23.  62.  41.  29.]
 [106.  21.  62.  42.  10.]
 [125.  23.  70.  29.  43.]
 [135.  20.  73.   5.  36.]]


In [76]:
#task 3
lowestincome=np.where(shop[:,2]==np.min(shop[:,2]))
print("Customers with lowest income")
print(shop[lowestincome])
print('')
highestincome=np.where(shop[:,2]==np.max(shop[:,2]))
print("Customers with highest income")
print(shop[highestincome])

Customers with lowest income
[[ 1. 19. 15. 39.]
 [ 2. 21. 15. 81.]]

Customers with highest income
[[199.  32. 137.  18.]
 [200.  30. 137.  83.]]


In [91]:
#task 4
disc=np.where((shop[:,3]>75) & (shop[:,2]>35) & (shop[:,1]<45))
print(shop[disc])
len(shop)

[[ 42.  24.  38.  92.  22.]
 [124.  39.  69.  91.  38.]
 [126.  31.  70.  77.  35.]
 [128.  40.  71.  95.  37.]
 [136.  29.  73.  88.  22.]
 [142.  32.  75.  93.  16.]
 [144.  32.  76.  87.  35.]
 [146.  28.  77.  97.  36.]
 [150.  34.  78.  90.  33.]
 [152.  39.  78.  88.  19.]
 [154.  38.  78.  76.  38.]
 [156.  27.  78.  89.  19.]
 [158.  30.  78.  78.  45.]
 [162.  29.  79.  83.  45.]
 [164.  31.  81.  93.  35.]
 [168.  33.  86.  95.  20.]
 [174.  36.  87.  92.  16.]
 [176.  30.  88.  86.  13.]
 [180.  35.  93.  90.  36.]
 [182.  32.  97.  86.  14.]
 [184.  29.  98.  88.  45.]
 [186.  30.  99.  97.  25.]
 [190.  36. 103.  85.  14.]
 [194.  38. 113.  91.  32.]
 [196.  35. 120.  79.  21.]
 [200.  30. 137.  83.  40.]]


200

In [84]:
#task 5
discount=np.array(np.random.randint(10,50,len(shop)))
shop=np.insert(shop,4,discount,axis=1)
shop

array([[  1.,  19.,  15.,  39.,  17.],
       [  2.,  21.,  15.,  81.,  20.],
       [  3.,  20.,  16.,   6.,  43.],
       [  4.,  23.,  16.,  77.,  44.],
       [  5.,  31.,  17.,  40.,  25.],
       [  6.,  22.,  17.,  76.,  22.],
       [  7.,  35.,  18.,   6.,  35.],
       [  8.,  23.,  18.,  94.,  39.],
       [  9.,  64.,  19.,   3.,  11.],
       [ 10.,  30.,  19.,  72.,  48.],
       [ 11.,  67.,  19.,  14.,  13.],
       [ 12.,  35.,  19.,  99.,  47.],
       [ 13.,  58.,  20.,  15.,  29.],
       [ 14.,  24.,  20.,  77.,  35.],
       [ 15.,  37.,  20.,  13.,  12.],
       [ 16.,  22.,  20.,  79.,  15.],
       [ 17.,  35.,  21.,  35.,  13.],
       [ 18.,  20.,  21.,  66.,  38.],
       [ 19.,  52.,  23.,  29.,  45.],
       [ 20.,  35.,  23.,  98.,  27.],
       [ 21.,  35.,  24.,  35.,  27.],
       [ 22.,  25.,  24.,  73.,  10.],
       [ 23.,  46.,  25.,   5.,  10.],
       [ 24.,  31.,  25.,  73.,  43.],
       [ 25.,  54.,  28.,  14.,  29.],
       [ 26.,  29.,  28.,

In [87]:
#task 6
discountmorethan45=np.where(shop[:,4]>45)
print("Customers with discount more than 45%")
print(shop[discountmorethan45])

Customers with discount more than 45%
[[ 10.  30.  19.  72.  48.]
 [ 12.  35.  19.  99.  47.]
 [ 26.  29.  28.  82.  49.]
 [ 39.  36.  37.  26.  48.]
 [ 43.  48.  39.  36.  48.]
 [ 48.  27.  40.  47.  49.]
 [ 60.  53.  46.  46.  47.]
 [ 73.  60.  50.  49.  48.]
 [ 82.  38.  54.  55.  47.]
 [ 91.  68.  59.  55.  49.]
 [ 98.  27.  60.  50.  47.]
 [116.  19.  65.  50.  47.]
 [122.  38.  67.  40.  46.]
 [155.  47.  78.  16.  47.]
 [157.  37.  78.   1.  49.]
 [159.  34.  78.   1.  46.]
 [172.  28.  87.  75.  48.]]
