In [4]:
import numpy as np

In [13]:
#task 1  
hr=np.arange(0,500)
finance=np.arange(500,1000)
sales=np.arange(1000,1500)
it=np.arange(1500,2000)
print(hr)
print(finance)
print(sales)
print(it)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

In [20]:
#task 2
hrsalary=np.random.randint(25000,50000,500)
financesalary=1.25*hrsalary
salessalary=0.5*financesalary
itsalary=5000+hrsalary
print("HR")
print(hrsalary)
print("Finance")
print(financesalary)
print("Sales")
print(salessalary)
print("IT")
print(itsalary)

HR
[37759 44595 39237 45531 27983 36352 28825 35501 32791 25915 39367 31359
 49390 41338 34607 31532 25620 39764 28430 25193 47138 40473 32920 30984
 41517 38218 47342 34848 29837 42781 47472 39607 47355 32404 49395 37830
 48729 27356 26492 39280 36145 31115 34950 30950 34391 29413 46698 34896
 42644 25724 28901 30873 37872 25699 34725 31459 36739 45173 43697 49073
 29106 35448 42302 33551 26634 34607 49232 42506 48115 42492 39930 27401
 49421 34229 45787 49814 34011 42592 33034 40789 42738 48906 44373 48378
 37174 37250 28216 30861 32460 36088 49100 26084 31215 44242 46631 43283
 43976 45221 25938 34505 46793 36544 25606 43479 37968 25493 31297 26919
 31908 47454 35913 26131 25336 42114 32767 35786 30947 47286 47109 26191
 44342 31509 25590 25670 31540 41704 40135 43195 30196 36999 37591 39058
 26917 35989 35724 27384 46346 46818 42236 36742 39655 45105 37392 45262
 38785 45353 33139 48065 34253 38460 27491 30857 43239 36535 48538 34308
 33340 44911 49728 38292 26531 25613 34911 26904

In [24]:
#task 3
hrtotalctc=np.sum(hrsalary)
financetotalctc=np.sum(financesalary)
salestotalctc=np.sum(salessalary)
ittotalctc=np.sum(itsalary)
print("HR department total spend is",hrtotalctc)
print("Finance department total spend is",financetotalctc)
print("Sales department total spend is",salestotalctc)
print("IT department total spend is",ittotalctc)

HR department total spend is 18571824
Finance department total spend is 23214780.0
Sales department total spend is 11607390.0
IT department total spend is 21071824


In [31]:
#task 4
hrpaysort=np.sort(hrsalary)
hrpaysortdesc=hrpaysort[::-1]
print("Top 10 earnings in HR")
print(hrpaysortdesc[0:10])
financepaysort=np.sort(financesalary)
financepaysortdesc=financepaysort[::-1]
print("Top 10 earnings in Finance")
print(financepaysortdesc[0:10])

Top 10 earnings in HR
[49972 49814 49762 49733 49728 49706 49663 49585 49571 49521]
Top 10 earnings in Finance
[62465.   62267.5  62202.5  62166.25 62160.   62132.5  62078.75 61981.25
 61963.75 61901.25]


In [158]:
#task 5
allsalary=np.concatenate((hrsalary,financesalary,salessalary,itsalary))
allsalarymorethan45k=np.where(allsalary>45000)
allsalary[allsalarymorethan45k]*1.1
print(allsalary)

salespay=allsalary[1000:1500]
itpay=allsalary[1500:2000]
salespaymorethan45k=np.where(salespay>45000)
itpaymorethan45k=np.where(itpay>45000)
print("There are",len(salespay[salespaymorethan45k])," employees in Sales department and",len(itpay[itpaymorethan45k]),"employees in IT department whom earn more than $45000")

[37759. 44595. 39237. ... 51359. 43242. 48593.]
There are 0  employees in Sales department and 186 employees in IT department whom earn more than $45000


In [209]:
#task 6
salespaylessthan45k=np.where(salespay<45000)
salespay1=salespay[salespaylessthan45k]*1.1
print(salespay1)
itpay1=allsalary[1500:2000]
hrpay1=allsalary[0:500]
financepay1=allsalary[500:1000]
newpay=np.concatenate((hrpay1,financepay1,salespay1,itpay1))
print(newpay)

[25959.3125 30659.0625 26975.4375 31302.5625 19238.3125 24992.
 19817.1875 24406.9375 22543.8125 17816.5625 27064.8125 21559.3125
 33955.625  28419.875  23792.3125 21678.25   17613.75   27337.75
 19545.625  17320.1875 32407.375  27825.1875 22632.5    21301.5
 28542.9375 26274.875  32547.625  23958.     20512.9375 29411.9375
 32637.     27229.8125 32556.5625 22277.75   33959.0625 26008.125
 33501.1875 18807.25   18213.25   27005.     24849.6875 21391.5625
 24028.125  21278.125  23643.8125 20221.4375 32104.875  23991.
 29317.75   17685.25   19869.4375 21225.1875 26037.     17668.0625
 23873.4375 21628.0625 25258.0625 31056.4375 30041.6875 33737.6875
 20010.375  24370.5    29082.625  23066.3125 18310.875  23792.3125
 33847.     29222.875  33079.0625 29213.25   27451.875  18838.1875
 33976.9375 23532.4375 31478.5625 34247.125  23382.5625 29282.
 22710.875  28042.4375 29382.375  33622.875  30506.4375 33259.875
 25557.125  25609.375  19398.5    21216.9375 22316.25   24810.5
 33756.25   17932

In [185]:
#task 1
import os
os.getcwd()


'D:\\darthsai'

In [186]:
import numpy as np
from numpy import genfromtxt
college=genfromtxt("DS1_C4_S1_AdmissionPredict_Data_Practice.csv",delimiter=',',skip_header=1)
college

array([[  1.  , 337.  , 118.  , ...,   9.65,   1.  ,   0.92],
       [  2.  , 324.  , 107.  , ...,   8.87,   1.  ,   0.76],
       [  3.  , 316.  , 104.  , ...,   8.  ,   1.  ,   0.72],
       ...,
       [398.  , 330.  , 116.  , ...,   9.45,   1.  ,   0.91],
       [399.  , 312.  , 103.  , ...,   8.78,   0.  ,   0.67],
       [400.  , 333.  , 117.  , ...,   9.66,   1.  ,   0.95]])

In [189]:
gre=np.where(college[:,1]>320)
print(college[gre,:])
print("There are",np.size(gre),"students who scored above 320 in GRE")

[[[  1.   337.   118.   ...   9.65   1.     0.92]
  [  2.   324.   107.   ...   8.87   1.     0.76]
  [  4.   322.   110.   ...   8.67   1.     0.8 ]
  ...
  [397.   325.   107.   ...   9.11   1.     0.84]
  [398.   330.   116.   ...   9.45   1.     0.91]
  [400.   333.   117.   ...   9.66   1.     0.95]]]
There are 163 students who scored above 320 in GRE


In [191]:
toefl=np.where(college[:,2]>110)
print("There are",np.size(toefl),"students who scored above 110 in TOEFL")

[[[  1.   337.   118.   ...   9.65   1.     0.92]
  [  6.   330.   115.   ...   9.34   1.     0.9 ]
  [ 12.   327.   111.   ...   9.     1.     0.84]
  ...
  [395.   329.   111.   ...   9.23   1.     0.89]
  [398.   330.   116.   ...   9.45   1.     0.91]
  [400.   333.   117.   ...   9.66   1.     0.95]]]
There are 120 students who scored above 110 in TOEFL


In [239]:

scholarship=np.where((college[:,7]==1) & (college[:,1]>315) & (college[:,2]>115))
print(college[scholarship][:,0])
print("There are",len(college[scholarship]),"students who are eligible for scholarship for students with research experience and whose GRE score is greater   than 315 and TOEFL score is greater than 115.")
print(college[scholarship])

[  1.  23.  24.  25.  26.  33.  53.  71.  82.  98.  99. 108. 109. 121.
 122. 130. 139. 142. 144. 149. 152. 172. 177. 188. 194. 203. 204. 213.
 214. 215. 216. 260. 286. 287. 326. 338. 362. 373. 386. 398. 400.]
There are 41 students who are eligible for scholarship for students with research experience and whose GRE score is greater   than 315 and TOEFL score is greater than 115.
[[  1.   337.   118.     4.     4.5    4.5    9.65   1.     0.92]
 [ 23.   328.   116.     5.     5.     5.     9.5    1.     0.94]
 [ 24.   334.   119.     5.     5.     4.5    9.7    1.     0.95]
 [ 25.   336.   119.     5.     4.     3.5    9.8    1.     0.97]
 [ 26.   340.   120.     5.     4.5    4.5    9.6    1.     0.94]
 [ 33.   338.   118.     4.     3.     4.5    9.4    1.     0.91]
 [ 53.   334.   116.     4.     4.     3.     8.     1.     0.78]
 [ 71.   332.   118.     5.     5.     5.     9.64   1.     0.94]
 [ 82.   340.   120.     4.     5.     5.     9.5    1.     0.96]
 [ 98.   331.   120.     